Practical4/Models/GroupModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Practical4.Models
{
    public class GroupModel
    {
        [Display(Name = "Student Number")]
        public string StudentNum { get; set; }

        [Display(Name = "Name")]
        public string FirstName { get; set; }

        [Display(Name = "Surname")]
        public string LastName { get; set; }

        [Display(Name = "Email Address")]
        public string Email { get; set; }

        [Display(Name = "Link to Personal Page")]
        public string myLink { get; set; }
    }
}

Practical4/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace Practical4.Controllers
{
    public class GroupController : Controller
    {
        // GET: Group

        public ActionResult ListGroup()
        {
            List<Models.GroupModel> group = new List<Models.GroupModel>();

            group.Add(new Models.GroupModel { StudentNum = "u23684722", FirstName = "Vishal", LastName = "Bhagwan", Email = "u23684722@tuks.co.za", myLink = "/HTML/Person1.html" });
            group.Add(new Models.GroupModel { StudentNum = "u23585600", FirstName = "Callum", LastName = "Molver", Email = "u23585600@tuks.co.za", myLink = "/HTML/Person2.html" });
            group.Add(new Models.GroupModel { StudentNum = "u23582032", FirstName = "Pranavan", LastName = "Naidoo", Email = "u23582032@tuks.co.za", myLink = "/HTML/Person3.html" });
            group.Add(new Models.GroupModel { StudentNum = "u23430273", FirstName = "Maya", LastName = "Pillay", Email = "u23430273@tuks.co.za", myLink = "/HTML/Person4.html" });
            group.Add(new Models.GroupModel { StudentNum = "u23958301", FirstName = "Mahilan", LastName = "Naicker", Email = "u23958301@tuks.co.za", myLink = "/HTML/Person5.html" });

            return View(group);
        }
    }
}

Practical4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practical2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Practical4/Views/Group/ListGroup.cshtml
@model IEnumerable<Practical4.Models.GroupModel>

@{
    ViewBag.Title = "Study Group";
}

<link href="~/Content/TableStyle.css" rel="stylesheet" type="text/css" />

<h2>List of People</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StudentNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.myLink)
        </th>
        <th>
            Delete
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StudentNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <a href="@item.myLink" class="btn btn-primary">LINK</a>
            </td>
            <td>
                <button class="btn btn-primary" onclick="removeRow(this)">Delete</button>
            </td>
        </tr>
    }

</table>

<script>
    //Delete
    function removeRow(e) {
        e.parentElement.parentElement.remove();
    }


    //Highlight
    document.addEventListener("DOMContentLoaded", () => {
        const rows = document.querySelectorAll("table tr");
        rows.forEach((row, index) => {
            if (index === 0) return;
            const firstName = row.cells[1].innerText.trim();
            if (firstName.startsWith("M")) {
                row.style.color = "red";
            }
        });
    });
</script>

Practical4/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">Study Group</h1>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">

            <p>
                List of all the people in the study group, which their university information and some personal information.
            </p>
        </section>
    </div>
</main>

Practical4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Simple Starting Page", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            List of People
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("Complete List of People", "ListGroup", "Group", new { area = "" }, new { @class = "dropdown-item" })</li>
                            <li><a class="dropdown-item" href="~/HTML/Person1.html">Person 1</a></li>
                            <li><a class="dropdown-item" href="~/HTML/Person2.html">Person 2</a></li>
                            <li><a class="dropdown-item" href="~/HTML/Person3.html">Person 3</a></li>
                            <li><a class="dropdown-item" href="~/HTML/Person4.html">Person 4</a></li>
                            <li><a class="dropdown-item" href="~/HTML/Person5.html">Person 5</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Study Group</p>
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>